### PR TITLE
openai assisted provenance

### PR DESCRIPTION
**Pull request by benjaminleighton**
demonstrates using openai to assist in understanding complex provenance and modifying provenance

### CODE REVIEW

**Review by PeterBaker0 — COMMENTED** [review]
I ran the notebook fine. 

Just noted to Ben to watch the API keys (I know it was an artifact of getting it working locally). 

The content itself is fully mind blowing - the fact that the simply structured template query enables both comprehension and modification of the provenance in the desired syntactically valid serialisation is nuts. 

I'm trying to think about how this could be used in RRAP - generally we have a very high fence between the user and the raw prov document - but wouldn't it be cool to have a way to let users perform these kind of 'guided modifications' to provenance (even in our custom format).

**Comment by PeterBaker0** [comment]
I'm probably going to play more later and try some more complex modifications :)

**Comment by jyucsiro** [comment]
very cool. 

agree about the api key - do you want to keep it in? @benjaminleighton

**Comment by benjaminleighton** [comment]
Embarrased about the key (now destroyed!)

**Review by jyucsiro — APPROVED** [review]

**Pull request merged**
